// Generated by scripts/design-tokens.mjs. Edit contracts/design/tokens.json.
export const tokens = {
  "color": {
    "surface": {
      "canvas": "#f4f2f8",
      "default": "#ffffff",
      "panel": "#ffffff",
      "elevated": "#ede9f4",
      "inset": "#ede9f4",
      "immersive": "#000000",
      "scrim": "rgba(0, 0, 0, 0.72)"
    },
    "text": {
      "primary": "#151020",
      "secondary": "#40364f",
      "muted": "#655773",
      "inverse": "#ffffff",
      "onImmersive": "#ffffff"
    },
    "border": {
      "subtle": "#b6a9c8",
      "strong": "#80708f",
      "focus": "#006b73"
    },
    "action": {
      "primary": "#7c3aed",
      "hover": "#5b21b6",
      "secondary": "#ede9f4",
      "brand": "#7c3aed",
      "disabled": "#d5cede"
    },
    "status": {
      "success": "#006b2c",
      "warning": "#854a00",
      "danger": "#b42332",
      "info": "#00636b"
    },
    "statusSurface": {
      "success": "#e8fff0",
      "warning": "#fff3d6",
      "danger": "#fff0f2",
      "info": "#e5fcff"
    }
  },
  "space": {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 24,
    "6": 32,
    "7": 48
  },
  "radius": {
    "control": 0,
    "card": 0,
    "panel": 0,
    "hero": 0,
    "pill": 0
  },
  "size": {
    "tap": 48,
    "field": 56
  },
  "type": {
    "label": 12,
    "body": 15,
    "body-lg": 17,
    "title": 32,
    "display": 40
  }
} as const;

type Palette = { [Group in keyof typeof tokens.color]: { [Role in keyof (typeof tokens.color)[Group]]: string } };
export type Tokens = Omit<typeof tokens, 'color'> & { color: Palette };
export const darkTokens: Tokens = { ...tokens, color: {
  "surface": {
    "canvas": "#000000",
    "default": "#0d1117",
    "panel": "#0d1117",
    "elevated": "#1a1f2b",
    "inset": "#1a1f2b",
    "immersive": "#000000",
    "scrim": "rgba(0, 0, 0, 0.72)"
  },
  "text": {
    "primary": "#ffffff",
    "secondary": "#e2e8f0",
    "muted": "#a0aec0",
    "inverse": "#ffffff",
    "onImmersive": "#ffffff"
  },
  "border": {
    "subtle": "#465264",
    "strong": "#718096",
    "focus": "#00ffff"
  },
  "action": {
    "primary": "#7c3aed",
    "hover": "#5b21b6",
    "secondary": "#1a1f2b",
    "brand": "#7c3aed",
    "disabled": "#404654"
  },
  "status": {
    "success": "#00ff41",
    "warning": "#ffb000",
    "danger": "#ff6666",
    "info": "#00ffff"
  },
  "statusSurface": {
    "success": "#062d16",
    "warning": "#322200",
    "danger": "#330f16",
    "info": "#002c30"
  }
} };
