-- Alpha schema authority lives in backend/internal/app/schema.sql.
-- Do not run this file as an ordered migration; it intentionally does not
-- create tables.
-- This placeholder exists so the repository has an obvious future home for
-- ordered migrations when destructive changes, backfills, or production data
-- require them.
