import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);
const tokens = JSON.parse(readFileSync(new URL('contracts/design/tokens.json', root), 'utf8'));
function luminance(hex) {
  if (!/^#[0-9a-f]{6}$/i.test(hex)) throw new Error(`Contrast colors must use six-digit hex: ${hex}`);
  const channels = hex.slice(1).match(/../g).map((channel) => parseInt(channel, 16) / 255)
    .map((channel) => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4);
  return channels[0] * 0.2126 + channels[1] * 0.7152 + channels[2] * 0.0722;
}
function checkContrast(label, foreground, background) {
  const values = [luminance(foreground), luminance(background)].sort((a, b) => a - b);
  const ratio = (values[1] + 0.05) / (values[0] + 0.05);
  if (ratio < 4.5) throw new Error(`${label}: ${ratio.toFixed(2)}:1 contrast; normal text requires 4.5:1.`);
}
for (const [mode, color] of Object.entries({ light: tokens.color, dark: tokens.darkColor })) {
  for (const [name, foreground] of Object.entries(color.text)) {
    if (name === 'inverse' || name === 'onImmersive') continue;
    for (const surface of ['canvas', 'panel', 'inset']) checkContrast(`${mode}: ${name} on ${surface}`, foreground, color.surface[surface]);
  }
  checkContrast(`${mode}: Primary action`, color.text.inverse, color.action.primary);
  checkContrast(`${mode}: Immersive copy`, color.text.onImmersive, color.surface.immersive);
  for (const [tone, foreground] of Object.entries(color.status)) checkContrast(`${mode}: ${tone}`, foreground, color.statusSurface[tone]);
}
const { darkColor, ...lightTokens } = tokens;
const declarations = [];
const names = { text: 'fg', border: 'stroke', statusSurface: 'status-surface' };
function colorDeclarations(color) {
  return Object.entries(color).flatMap(([group, values]) => Object.entries(values).map(([name, value]) =>
    `  --color-${names[group] ?? group}-${name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)}: ${value};`));
}
declarations.push(...colorDeclarations(tokens.color));
declarations.push('  --color-fg-accent: var(--color-fg-primary);');
for (const [name, value] of Object.entries(tokens.radius)) declarations.push(`  --radius-${name}: ${value}px;`);
for (const [name, value] of Object.entries(tokens.space)) declarations.push(`  --spacing-space-${name}: ${value}px;`);
declarations.push(`  --spacing-touch: ${tokens.size.tap}px;`, `  --spacing-field: ${tokens.size.field}px;`);
for (const [name, value] of Object.entries(tokens.type)) declarations.push(`  --text-${name}: ${value}px;`);
const heading = '/* Generated by scripts/design-tokens.mjs. Edit contracts/design/tokens.json. */';
const base = `${heading}\n@theme {\n${declarations.join('\n')}\n}\n`;
const dark = colorDeclarations(darkColor).join('\n');
const css = `${base}\n:root { color-scheme: light; }\n:root[data-theme="dark"] {\n${dark}\n  color-scheme: dark;\n}\n@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]):not([data-theme="dark"]) {\n${dark}\n    color-scheme: dark;\n  }\n}\n`;
const nativeCSS = `${base}\n@layer theme {\n  :root {\n    @variant light {\n${colorDeclarations(tokens.color).join('\n')}\n    }\n    @variant dark {\n${dark}\n    }\n  }\n}\n`;
const ts = `// Generated by scripts/design-tokens.mjs. Edit contracts/design/tokens.json.\nexport const tokens = ${JSON.stringify(lightTokens, null, 2)} as const;\n\ntype Palette = { [Group in keyof typeof tokens.color]: { [Role in keyof (typeof tokens.color)[Group]]: string } };\nexport type Tokens = Omit<typeof tokens, 'color'> & { color: Palette };\nexport const darkTokens: Tokens = { ...tokens, color: ${JSON.stringify(darkColor, null, 2)} };\n`;
const outputs = {
  'web/src/ui/tokens.css': css,
  'mobile/src/theme/tokens.css': nativeCSS,
  'mobile/src/theme/tokens.ts': ts,
};
let stale = false;
for (const [path, content] of Object.entries(outputs)) {
  const target = new URL(path, root);
  if (process.argv.includes('--check')) {
    let actual;
    try { actual = readFileSync(target, 'utf8'); } catch { actual = ''; }
    if (actual !== content) { console.error(`Stale design tokens: ${fileURLToPath(target)}`); stale = true; }
  } else writeFileSync(target, content);
}
if (stale) process.exitCode = 1;
else console.log(process.argv.includes('--check') ? 'Design tokens match both clients.' : 'Generated design tokens for web and mobile.');
