import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);
const tokens = JSON.parse(readFileSync(new URL('contracts/design/tokens.json', root), 'utf8'));
function luminance(hex) {
  if (!/^#[0-9a-f]{6}$/i.test(hex)) throw new Error(`Contrast colors must use six-digit hex: ${hex}`);
  const channels = hex.slice(1).match(/../g).map((channel) => parseInt(channel, 16) / 255)
    .map((channel) => channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4);
  return channels[0] * 0.2126 + channels[1] * 0.7152 + channels[2] * 0.0722;
}
function checkContrast(label, foreground, background) {
  const values = [luminance(foreground), luminance(background)].sort((a, b) => a - b);
  const ratio = (values[1] + 0.05) / (values[0] + 0.05);
  if (ratio < 4.5) throw new Error(`${label}: ${ratio.toFixed(2)}:1 contrast; normal text requires 4.5:1.`);
}
for (const [name, foreground] of Object.entries(tokens.color.text)) {
  if (name === 'inverse') continue;
  for (const surface of ['canvas', 'panel', 'inset']) checkContrast(`${name} on ${surface}`, foreground, tokens.color.surface[surface]);
}
checkContrast('Primary action', tokens.color.text.inverse, tokens.color.action.primary);
for (const [tone, foreground] of Object.entries(tokens.color.status)) checkContrast(tone, foreground, tokens.color.statusSurface[tone]);
const declarations = [];
const names = { text: 'fg', border: 'stroke', statusSurface: 'status-surface' };
for (const [group, values] of Object.entries(tokens.color)) {
  for (const [name, value] of Object.entries(values)) {
    declarations.push(`  --color-${names[group] ?? group}-${name}: ${value};`);
  }
}
declarations.push('  --color-fg-accent: var(--color-fg-primary);');
for (const [name, value] of Object.entries(tokens.radius)) declarations.push(`  --radius-${name}: ${value}px;`);
for (const [name, value] of Object.entries(tokens.space)) declarations.push(`  --spacing-space-${name}: ${value}px;`);
declarations.push(`  --spacing-touch: ${tokens.size.tap}px;`, `  --spacing-field: ${tokens.size.field}px;`);
for (const [name, value] of Object.entries(tokens.type)) declarations.push(`  --text-${name}: ${value}px;`);
const css = `/* Generated by scripts/design-tokens.mjs. Edit contracts/design/tokens.json. */\n@theme {\n${declarations.join('\n')}\n}\n`;
const ts = `// Generated by scripts/design-tokens.mjs. Edit contracts/design/tokens.json.\nexport const tokens = ${JSON.stringify(tokens, null, 2)} as const;\n\nexport type Tokens = typeof tokens;\n`;
const outputs = {
  'web/src/ui/tokens.css': css,
  'mobile/src/theme/tokens.css': css,
  'mobile/src/theme/tokens.ts': ts,
};
let stale = false;
for (const [path, content] of Object.entries(outputs)) {
  const target = new URL(path, root);
  if (process.argv.includes('--check')) {
    let actual;
    try { actual = readFileSync(target, 'utf8'); } catch { actual = ''; }
    if (actual !== content) { console.error(`Stale design tokens: ${fileURLToPath(target)}`); stale = true; }
  } else writeFileSync(target, content);
}
if (stale) process.exitCode = 1;
else console.log(process.argv.includes('--check') ? 'Design tokens match both clients.' : 'Generated design tokens for web and mobile.');
